version: '3.8'

services:
  dns-resolver:
    image: dns-resolver:1.0.0
    build: .
    env_file:
      - .env
    container_name: dns-resolver
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - redis
    command: npm start
    networks:
      - redis-network

  redis:
    image: "redis:7.0-alpine"
    container_name: "redis-service"
    hostname: "redis.service"
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - redis-network

networks:
  redis-network: